name: 'build'

on:
  workflow_dispatch:
  push:
    branches:
      - release

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest'
            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-22.04'
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt update -y
          sudo apt install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf openssl

      - name: install pnpm
        uses: pnpm/action-setup@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'

      - name: install rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: '. -> target'

      - name: install frontend dependencies
        run: pnpm install --frozen-lockfile

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__
          releaseName: 'v__VERSION__'
          releaseBody: |
            get your bromomethane fix on linux and windows:
            - the `.exe` installer for windows
            - the `.deb` package for debian and ubuntu based distros
            - the `.rpm` package for fedora, opensuse, redhat and friends
            - `curl -fsSL https://raw.githubusercontent.com/kasimeka/bromomethane/refs/heads/main/scripts/linux/pkgbuild/arch-install.sh | bash` on archlinux to download and install the deb package
            - `.AppImage` portable executable on steam deck, other distros and recommended as a fallback if any of the distro-specific packages don't work well for your setup
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}
